spring:
  security:
    oauth2:
      client:
        registration:
          smartym:
            provider: smartym
            client-id: HKGzRFKpSVjSpTPQ
            client-secret: ovnLjsKEEciCxjwmeHZSB
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/smartym"
            scope: aisp, cbpii, pisp
            additional-parameters-when-request-for-access-token:
              scope: aisp, cbpii, pisp
            client-authentication-method: client_secret_post
            authenticationScheme: header
        provider:
          smartym:
            authorization-uri: http://89.38.131.219:8081/signin
            token-uri: http://89.38.131.219:8081/token
            user-name-attribute: name
service:
  smartym:
    payment-url: http://89.38.131.219:8081/payment-requests
    payment-base-url: http://89.38.131.219:8081/
    payment-send-type: OKHTTP3_ASYNC


